### ISSUE TITLE
Any possibility of fixing the GUI/HUD scaling with this fix?

### ISSUE THREAD

**Issue by ViperAcidZX** [emoose/OutRun2006Tweaks#2]
I'm curious if there's a possibility to fix the stretched HUD and/or GUI elements down the road with this mod? It has been one of the long standing issues that annoyed me with the PC version of the game (I can tolerate the stretched menus despite this).

**Comment by DonelBueno** [comment]
I saw your commit for fixing the strechted HUD and the 4:3 mode works nicely for the most part:

Menus after the "Press Enter" screen should have black borders intead of white borders, also the borders should start at the point where the aspect 4:3 ends so it doesn't show garbage at the sides:
![OR2006C2C_2024_06_28_17_29_55_746](https://github.com/emoose/OutRun2006Tweaks/assets/4239694/fbdaa01f-42af-44ef-b732-33188374e339)
![OR2006C2C_2024_06_28_17_29_55_748](https://github.com/emoose/OutRun2006Tweaks/assets/4239694/7a2d6cb8-5152-49d8-8863-754922d401a3)

The girlfirend silhouette during races is not adjusted:
![OR2006C2C_2024_06_28_17_31_35_120](https://github.com/emoose/OutRun2006Tweaks/assets/4239694/883ce2c0-eac2-42c6-9480-b9bfe4581264)
![OR2006C2C_2024_06_28_17_33_53_351](https://github.com/emoose/OutRun2006Tweaks/assets/4239694/a4c14eb6-d127-4d5a-955e-9dfced99709d)

**Comment by emoose** [comment]
Ah seems the girlfriend icon was using some other sprite func to draw, didn't look into that much since it was pretty complicated, but think I got it fixed now (at least the GF icon seems fixed, but looks like that func can handle 3 different types of sprite, not sure if all 3 are working properly yet...)

Figured out a more accurate way to do what online arcade does for the scaling too, comparing screenshots it matches pretty much 1:1 now 😸 
There are still a bunch of cases where online arcade disables the scaling which I haven't worked out purpose of yet though, so could still be some things not getting scaled correctly, so far I've noticed the position markers above rival cars sometimes glitch out, and the "special request" arrow also flies off screen.
Good chance other stuff probably needs fixing too, if you notice anything else broken please let me know.

(also it seems online arcade actually left the race position HUD element not scaled properly, https://youtu.be/-UqxjFgGvhk?t=39 has it showing much further left than the actual "Position" text -- the new code should match this non-scaled position HUD too, might try finding a proper fix for it later on...)

**Comment by emoose** [comment]
Thanks for taking a look, hadn't actually unlocked those fruit missions yet so didn't know about those, should be fixed now.

The rank sprite should be slightly adjusted now but not sure if it's perfect yet, seems to disappear very quickly in the C2C mode too while the heart attack mode has it stay on screen longer, not really sure why.

Still trying to find where "special request" sprite gets drawn, hopefully might find code for it soon.

**Comment by DonelBueno** [comment]
The rank sprite looks the same here, no changes at all compared to the old version:
![1](https://github.com/emoose/OutRun2006Tweaks/assets/4239694/f4e0d296-6080-47ec-b2e6-c90684e632fa)
![2](https://github.com/emoose/OutRun2006Tweaks/assets/4239694/532f8b31-d989-4791-b262-e2be9492e5f8)

Here is how it looks without your fix:
![OR2006C2C_2024_07_01_21_44_40_662](https://github.com/emoose/OutRun2006Tweaks/assets/4239694/2732521b-0514-456a-b70e-aa885eeda730)

So the position is actually in line with the original behavior, it looks odd because there are more letters at the same space, so you could relocate it only when the rank is AA or AAA.

**Comment by lance8765** [comment]
You guys are on fire lmao, i left at 62-63 commits and now they're 75.

**Comment by emoose** [comment]
>Letterboxed HUD activates as soon as you reach the finish line instead of only when going back to the menus.

Sadly seems there's cut-off sprites that show up if it activates later:
![OR2006C2C_HqdbhK4KC7](https://github.com/emoose/OutRun2006Tweaks/assets/1755499/2bb0c4a1-da4a-46eb-968e-16f0c0475cc5)

and this loading spinner sprite when you exit a race:
![OR2006C2C_mO5HDvmX5D](https://github.com/emoose/OutRun2006Tweaks/assets/1755499/34e96239-cec2-42d9-82b5-e3e65fe6ad24)

Maybe there's some way to only activate it when that ranking screen / loading spinner is shown, will try seeing if there's a way to detect it.

**Comment by emoose** [comment]
Since this is getting a little attention now I've posted a 0.4 release with the current UI changes (thanks to everyone that's shared it!)

Not much really changed in that from the last artifact builds, the issues DonelBueno mentioned are still present but hopefully aren't big enough to ruin it for anyone, will probably leave this issue page open until those are done.

(fyi 0.4 did switch UIScalingMode, now `UIScalingMode = 1` is the OnlineArcade scaling while `UIScalingMode = 2` is 4:3)

**Comment by Dekaid0011** [comment]
Rev Indicator isn't aligned when using manual transmission:

![OR2006C2C_6LeEeNozOJ](https://github.com/emoose/OutRun2006Tweaks/assets/143886581/4f100654-8f3a-4e4c-ad91-e950758c60df)

How it's supposed to look:

![firefox_2xzQ1qO8GP](https://github.com/emoose/OutRun2006Tweaks/assets/143886581/d5518bd1-31bb-44ff-b3f7-523124ba9834)

**Comment by emoose** [comment]
Ahh forgot to check manual transmission mode, rev indicator should be fixed in https://github.com/emoose/OutRun2006Tweaks/actions/runs/9809520648
Will take a look at the sector time issue shortly.

**Comment by emoose** [comment]
The issue in #26 should be fixed now hopefully, was just missing a single hook in the ghost time display func (seems online arcade was also missing the fix there too..)

Also made it so letterboxing won't show up on the GOAL screen, since it would cut off things like score/ghost time/etc displays.

There's still the issue with the flag man & loading sprite cutoffs, hopefully can figure out something for them eventually.

Will probably push out 0.4.1 with these in a moment.

**Comment by Dekaid0011** [comment]
Confirming both the rev indicator and sector times are now fixed. I also just noticed you can see in #26 the MT next to Tuned under the Tachometer isn't aligned, if I remember correctly this was also an issue in other versions so it might also be intended but looks off.

Also thanks for your work, this has already made the PC version by far the best option to play now.

**Comment by DonelBueno** [comment]
The AT is also not alligned, they are used on time attack mode.

**Comment by ViperAcidZX** [comment]
> > Letterboxed HUD activates as soon as you reach the finish line instead of only when going back to the menus.
> 
> Sadly seems there's cut-off sprites that show up if it activates later: ![OR2006C2C_HqdbhK4KC7](https://private-user-images.githubusercontent.com/1755499/345709338-2bb0c4a1-da4a-46eb-968e-16f0c0475cc5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMDM1MDEsIm5iZiI6MTcyMDMwMzIwMSwicGF0aCI6Ii8xNzU1NDk5LzM0NTcwOTMzOC0yYmIwYzRhMS1kYTRhLTQ2ZWItOTY4ZS0xNmYwYzA0NzVjYzUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDZUMjIwMDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWEwYTA1NDJmNTMxYjM3NzkzMmVjZWJhMjMyMDM0NDVhOThhMTlkMTRiZDAyMGUwZWJhYjJkYTNlYWQzMTY2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WUX_t5VEfZAfmB2FJP8a1wHp5F0xqYaM4lGVWHGCfhc)
> 
> and this loading spinner sprite when you exit a race: ![OR2006C2C_mO5HDvmX5D](https://private-user-images.githubusercontent.com/1755499/345709377-34e96239-cec2-42d9-82b5-e3e65fe6ad24.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMDM1MDEsIm5iZiI6MTcyMDMwMzIwMSwicGF0aCI6Ii8xNzU1NDk5LzM0NTcwOTM3Ny0zNGU5NjIzOS1jZWMyLTQyZDktODJiNS1lM2U2NWZlNmFkMjQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDZUMjIwMDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWM4YmYxM2ViNzBkNGEyNGJhYjQ5ZDI5NjhhZGFlY2NiNjY1OWMzMzA2Y2JiZTk4YjRiYmJjNjA0ZTJmYjMyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CEef88pCb_GyXy5VMNpBPC-sZibqRJNZe43IopUI0v0)
> 
> Maybe there's some way to only activate it when that ranking screen / loading spinner is shown, will try seeing if there's a way to detect it.

Could it be possible that texture packs can fill in the missing parts of the UI graphics that are cut off at the 4:3 edges? Also I am still getting the GOAL/Game Over screen getting pillarboxed in Singleplayer → OutRun mode.

**Comment by ArhumMK** [comment]
Special Requests have a part of the HUD on the far right edge of the screen, looks to be same as the arrow under the "Next Stage" text?
![image](https://github.com/emoose/OutRun2006Tweaks/assets/70807030/b9eb0515-ea7a-4631-a166-54a4d11f2e68)
![image2](https://github.com/emoose/OutRun2006Tweaks/assets/70807030/4c968c14-9c7f-4a97-afc0-0f8f89934624)

**Comment by emoose** [comment]
Still no luck with the special requests arrow sadly, seems there's not actually any specific code that handles moving it, think it's actually some kind of animation data kept with the sprite, not sure how game is reading in that data yet...

**Comment by moocowmoomoo** [comment]
Thanks so much for all this hard work emoose! I'm the type of idiot who plays racing games on a triple monitor setup with a wheel. Previously having the HUD stretch across all 3 screens made it a nightmare to play, so thanks a massive bunch for the 4:3 option! The game is much more playable now. It's a huge difference! <3

However, I would rather have the HUD elements sit closer to the edge of the middle monitor, to feel less cramped, but on triple screens with "UIScalingMode=1" the adjustments put the left and right elements halfway over the edge of the middle monitor and half onto the side monitors, dividing them up with the monitor bezel. So my only request would be that you also consider adding a 16:9 option to the .ini (maybe UIScalingMode=3), so that the HUD feels less cramped on a triple monitor setup.

**Comment by emoose** [comment]
I might change `UIScalingMode = 1` as the default in next release, pains me to see people setting up Tweaks without bothering with the INI and then making videos with stretched UI everywhere.

If anyone has any real reason to object to it let me know (keep in mind that it can always be reverted with 1 INI change, so purists who play C2C for the stretched textures can still have them)

@moocowmoomoo sorry for lack of reply to this, did try taking a look at implementing 16:9 but wasn't able to get it working properly with the current code yet, I'm sure there should be some way to setup a custom "safe zone" for the UI to render inside though.

**Comment by thegreatprophetzarquon** [comment]
I agree it should be the default. However, the latest action build has the REV indicator in the right spot, but when the red light turns on its not aligned with the circle underneath it.

**Comment by DonelBueno** [comment]
> I agree it should be the default. However, the latest action build has the REV indicator in the right spot, but when the red light turns on its not aligned with the circle underneath it.

Check the discord, you are probably using a misaligned texture from "Higher.Quality.UI.Sprites.v3 zip".

**Comment by thegreatprophetzarquon** [comment]
And it so it was was my fault, lol. Fixed and thank you! It does still look like the red light's just slightly too far to the right in scaling mode 1 as compared with 0 and 2.

**Comment by emoose** [comment]
Guess this can be closed since UIScalingMode is mostly working fine now, but if you notice any positioning issues with UI text please post about it here: #94
